import { Provider } from "../components/ui/provider.jsx";
import { Center } from "@chakra-ui/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>
          <Center w="100vw" h="100vh">
            {children}
          </Center>
        </Provider>
      </body>
    </html>
  );
}
